<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <material name="gray" />
            <collision>
                <geometry>
                    <box size="${camera_length} ${camera_width} ${camera_height}" />
                </geometry>                
            </collision>
            <xacro:box_inertia m="0.1" l="${camera_length}" w="${camera_width}" h="${camera_height}"
                               xyz="0 0 0" rpy="0 0 0" />
        </visual>
    </link>

    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <sensor name="camera_sensor" type="camera">
            <pose>0 0 0 0 0 0</pose>    <!--origin of the camera related to camera_link-->
            <visualize>true</visualize>    <!--projection in gazebo-->
            <update_rate>10.0</update_rate> <!--Hertz-->
            <camera>
                <!--I passed this-->
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link</frame_name> <!--where the camera attached-->
            </plugin>
        </sensor>
    </gazebo>


    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${(base_length + camera_length) / 2.0} 0 ${base_height / 2.0}" rpy="0 0 0" />
    </joint>

</robot>